name: soso
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.42.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.1
  - pip=23.1.2
  - python=3.11.4
  - readline=8.2
  - setuptools=68.0.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - alabaster==0.7.13
      - anyascii==0.3.2
      - astroid==2.15.6
      - babel==2.12.1
      - black==23.7.0
      - bleach==6.0.0
      - certifi==2023.5.7
      - charset-normalizer==3.2.0
      - click==8.1.5
      - click-log==0.4.0
      - colorama==0.4.6
      - coverage==7.2.7
      - dill==0.3.6
      - docutils==0.20.1
      - dotty-dict==1.3.1
      - gitdb==4.0.10
      - gitpython==3.1.32
      - idna==3.4
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - iniconfig==2.0.0
      - invoke==2.2.0
      - isort==5.12.0
      - jaraco-classes==3.3.0
      - jinja2==3.1.2
      - keyring==24.2.0
      - lazy-object-proxy==1.9.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mccabe==0.7.0
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - more-itertools==9.1.0
      - mypy-extensions==1.0.0
      - myst-parser==2.0.0
      - packaging==23.1
      - pathspec==0.11.1
      - pkginfo==1.9.6
      - platformdirs==3.8.1
      - pluggy==1.2.0
      - pygments==2.15.1
      - pylint==2.17.4
      - pytest==7.4.0
      - pytest-cov==4.1.0
      - python-gitlab==3.15.0
      - python-semantic-release==7.34.6
      - pyyaml==6.0
      - readme-renderer==40.0
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - semver==2.13.0
      - six==1.16.0
      - smmap==5.0.0
      - snowballstemmer==2.2.0
      - sphinx==7.0.1
      - sphinx-autoapi==2.1.1
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - tomlkit==0.11.8
      - tqdm==4.65.0
      - twine==3.8.0
      - urllib3==2.0.3
      - webencodings==0.5.1
      - wrapt==1.15.0
      - zipp==3.16.2
prefix: /opt/miniconda3/envs/soso
