name: soso
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=1.0.0
  - annotated-types=0.7.0
  - anyio=4.12.1
  - astroid=4.0.4
  - babel=2.18.0
  - backoff=2.2.1
  - backports.zstd=1.3.0
  - black=26.1.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.1.8
  - click-option-group=0.5.6
  - colorama=0.4.6
  - coverage=7.13.4
  - daiquiri=3.0.0
  - deprecated=1.2.18
  - dill=0.4.1
  - docutils=0.22.4
  - dotty-dict=1.3.1
  - exceptiongroup=1.3.1
  - gitdb=4.0.12
  - gitpython=3.1.46
  - gql=4.0.0
  - graphql-core=3.2.7
  - h2=4.3.0
  - hpack=4.1.0
  - html5rdf=1.2.1
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - iniconfig=2.3.0
  - isodate=0.7.2
  - isort=7.0.0
  - jinja2=3.1.6
  - libcxx=21.1.8
  - libexpat=2.7.4
  - libffi=3.5.2
  - libiconv=1.18
  - liblzma=5.8.2
  - libsqlite=3.51.2
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mccabe=0.7.0
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - multidict=6.7.0
  - mypy_extensions=1.1.0
  - myst-parser=5.0.0
  - ncurses=6.5
  - openssl=3.6.1
  - owlrl=7.1.4
  - packaging=26.0
  - pathspec=1.0.4
  - pip=26.0.1
  - platformdirs=4.9.2
  - pluggy=1.6.0
  - prettytable=3.17.0
  - propcache=0.3.1
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pylint=4.0.4
  - pyparsing=3.3.2
  - pyshacl=0.31.0
  - pysocks=1.7.1
  - pytest=9.0.2
  - pytest-cov=7.0.0
  - python=3.11.14
  - python-gitlab=5.6.0
  - python-json-logger=2.0.7
  - python-semantic-release=10.5.3
  - python_abi=3.11
  - pytokens=0.4.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - rdflib=7.6.0
  - rdflib-with-html=7.6.0
  - readline=8.3
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - rich=14.3.2
  - roman-numerals=4.1.0
  - setuptools=82.0.0
  - shellingham=1.5.4
  - smmap=5.0.2
  - snowballstemmer=3.0.1
  - sphinx=9.0.4
  - sphinx-autoapi=3.7.0
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - stdlib-list=0.12.0
  - tk=8.6.13
  - tomli=2.4.0
  - tomlkit=0.14.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - wcwidth=0.6.0
  - wheel=0.46.3
  - wrapt=1.17.3
  - yaml=0.2.5
  - yarl=1.22.0
  - zipp=3.23.0
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/soso
