name: soso
channels:
  - conda-forge
  - defaults
dependencies:
  - pytest-cov
  - black
  - myst-parser
  - sphinx
  - pylint
  - pyshacl
  - requests
  - daiquiri
  - python-semantic-release
  - python=3.11
  - pytest
  - sphinx-autoapi
  - lxml
prefix: /opt/miniconda3/envs/soso
