name: soso
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=1.0.0
  - annotated-types=0.7.0
  - anyio=4.12.0
  - astroid=4.0.2
  - babel=2.17.0
  - backoff=2.2.1
  - backports.zstd=1.2.0
  - black=25.12.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.1.8
  - click-option-group=0.5.6
  - colorama=0.4.6
  - coverage=7.13.0
  - daiquiri=3.0.0
  - deprecated=1.2.18
  - dill=0.4.0
  - docutils=0.21.2
  - dotty-dict=1.3.1
  - exceptiongroup=1.3.1
  - gitdb=4.0.12
  - gitpython=3.1.45
  - gql=4.0.0
  - graphql-core=3.2.7
  - h2=4.3.0
  - hpack=4.1.0
  - html5rdf=1.2.1
  - hyperframe=6.1.0
  - idna=3.11
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - iniconfig=2.3.0
  - isodate=0.7.2
  - isort=7.0.0
  - jinja2=3.1.6
  - libcxx=21.1.7
  - libexpat=2.7.3
  - libffi=3.5.2
  - libiconv=1.18
  - liblzma=5.8.1
  - libsqlite=3.51.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.3
  - mccabe=0.7.0
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - multidict=6.6.3
  - mypy_extensions=1.1.0
  - myst-parser=4.0.1
  - ncurses=6.5
  - openssl=3.6.0
  - owlrl=7.1.4
  - packaging=25.0
  - pathspec=0.12.1
  - pip=25.3
  - platformdirs=4.5.1
  - pluggy=1.6.0
  - prettytable=3.17.0
  - propcache=0.3.1
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pylint=4.0.4
  - pyparsing=3.2.5
  - pyshacl=0.30.1
  - pysocks=1.7.1
  - pytest=9.0.2
  - pytest-cov=7.0.0
  - python=3.11.14
  - python-gitlab=5.6.0
  - python-json-logger=2.0.7
  - python-semantic-release=10.5.2
  - python_abi=3.11
  - pytokens=0.3.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - rdflib=7.5.0
  - rdflib-with-html=7.5.0
  - readline=8.2
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - rich=14.2.0
  - roman-numerals-py=3.1.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - smmap=5.0.2
  - snowballstemmer=3.0.1
  - sphinx=8.2.3
  - sphinx-autoapi=3.6.1
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - stdlib-list=0.12.0
  - tk=8.6.13
  - tomli=2.3.0
  - tomlkit=0.13.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - wcwidth=0.2.14
  - wheel=0.45.1
  - wrapt=1.17.3
  - yaml=0.2.5
  - yarl=1.22.0
  - zipp=3.23.0
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/soso
